# Generated by Django 5.2.7 on 2025-10-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_session_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
