# Generated by Django 5.2.7 on 2025-10-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_session_description_alter_session_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='description',
        ),
    ]
