# Generated by Django 5.2.7 on 2025-10-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_session_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sound',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
