# Generated by Django 5.2.7 on 2025-10-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='user',
        ),
    ]
